using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ScreenShoot : MonoBehaviour
{

    public Camera currentCamera;

    private Camera screenshot;

    // Start is called before the first frame update
    void Start()
    {
        screenshot = this.GetComponent<Camera>();
    }

    // Update is called once per frame
    void Update()
    {
        if (Input.GetMouseButtonDown(0))
        {

            screenshot.transform.position = currentCamera.transform.position;
            screenshot.transform.rotation = currentCamera.transform.rotation;

            Texture2D texture = RTImage(screenshot);

            //then Save To Disk as PNG
            string folderPath = "Assets/Screenshot"; // the path of your project folder
                                                     // ​
            if (!System.IO.Directory.Exists(folderPath)) // if this path does not exist yet
                System.IO.Directory.CreateDirectory(folderPath);  // it will get created

            byte[] bytes = texture.EncodeToPNG();
            var screenshotName =
                                   "ElectromagnetismVR_" +
                                   System.DateTime.Now.ToString("dd-MM-yyyy-HH-mm-ss") + // puts the current time right into the screenshot name
                                   ".png"; // put youre favorite data format here

            System.IO.File.WriteAllBytes(System.IO.Path.Combine(folderPath, screenshotName), bytes);
            Debug.Log(folderPath + screenshotName);
        }
    }

    // Take a "screenshot" of a camera's Render Texture.
    Texture2D RTImage(Camera camera)
    {
        // The Render Texture in RenderTexture.active is the one
        // that will be read by ReadPixels.
        var currentRT = RenderTexture.active;
        RenderTexture.active = camera.targetTexture;

        // Render the camera's view.
        camera.Render();

        // Make a new texture and read the active Render Texture into it.
        Texture2D image = new Texture2D(camera.targetTexture.width, camera.targetTexture.height);
        image.ReadPixels(new Rect(0, 0, camera.targetTexture.width, camera.targetTexture.height), 0, 0);
        image.Apply();

        // Replace the original active Render Texture.
        RenderTexture.active = currentRT;
        return image;
    }
}
